[package]
name = "raytracer-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
png = "0.17.7"
json = "0.12.4"
crossbeam = "0.8.2"
num_cpus = "1.15.0"